name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install
      
      - name: Run Tests with Coverage c8
        run: c8 mocha
      
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}

      

                    


